// ISO 3166-1 nationalities, alpha-3.
//
// The code, not the label, is what gets stored: `users.nationality` is matched
// against `country_nationality_restrictions.nationality_code`, which the data
// model declares as ISO alpha-3 (VarChar(3)). Until this existed, nationality
// was a free-text field on the profile form, so those two columns could never
// meet and the restriction table stayed unusable — the client's nationality
// was recorded but could never be acted on.
//
// Generated from ICU (Intl.DisplayNames in Arabic) rather than typed by hand,
// then sorted by Arabic name for display. Regenerate only if ISO changes.

export type Nationality = { code: string; alpha2: string; nameAr: string };

export const NATIONALITIES: readonly Nationality[] = [
  { code: "ISL", alpha2: "IS", nameAr: "آيسلندا" },
  { code: "ETH", alpha2: "ET", nameAr: "إثيوبيا" },
  { code: "AZE", alpha2: "AZ", nameAr: "أذربيجان" },
  { code: "ARM", alpha2: "AM", nameAr: "أرمينيا" },
  { code: "ABW", alpha2: "AW", nameAr: "أروبا" },
  { code: "ERI", alpha2: "ER", nameAr: "إريتريا" },
  { code: "ESP", alpha2: "ES", nameAr: "إسبانيا" },
  { code: "AUS", alpha2: "AU", nameAr: "أستراليا" },
  { code: "EST", alpha2: "EE", nameAr: "إستونيا" },
  { code: "ISR", alpha2: "IL", nameAr: "إسرائيل" },
  { code: "SWZ", alpha2: "SZ", nameAr: "إسواتيني" },
  { code: "AFG", alpha2: "AF", nameAr: "أفغانستان" },
  { code: "PSE", alpha2: "PS", nameAr: "الأراضي الفلسطينية" },
  { code: "ARG", alpha2: "AR", nameAr: "الأرجنتين" },
  { code: "JOR", alpha2: "JO", nameAr: "الأردن" },
  { code: "ATF", alpha2: "TF", nameAr: "الأقاليم الجنوبية الفرنسية" },
  { code: "IOT", alpha2: "IO", nameAr: "الإقليم البريطاني في المحيط الهندي" },
  { code: "ECU", alpha2: "EC", nameAr: "الإكوادور" },
  { code: "ARE", alpha2: "AE", nameAr: "الإمارات العربية المتحدة" },
  { code: "ALB", alpha2: "AL", nameAr: "ألبانيا" },
  { code: "BHR", alpha2: "BH", nameAr: "البحرين" },
  { code: "BRA", alpha2: "BR", nameAr: "البرازيل" },
  { code: "PRT", alpha2: "PT", nameAr: "البرتغال" },
  { code: "BIH", alpha2: "BA", nameAr: "البوسنة والهرسك" },
  { code: "CZE", alpha2: "CZ", nameAr: "التشيك" },
  { code: "MNE", alpha2: "ME", nameAr: "الجبل الأسود" },
  { code: "DZA", alpha2: "DZ", nameAr: "الجزائر" },
  { code: "DNK", alpha2: "DK", nameAr: "الدانمرك" },
  { code: "CPV", alpha2: "CV", nameAr: "الرأس الأخضر" },
  { code: "SLV", alpha2: "SV", nameAr: "السلفادور" },
  { code: "SEN", alpha2: "SN", nameAr: "السنغال" },
  { code: "SDN", alpha2: "SD", nameAr: "السودان" },
  { code: "SWE", alpha2: "SE", nameAr: "السويد" },
  { code: "ESH", alpha2: "EH", nameAr: "الصحراء الغربية" },
  { code: "SOM", alpha2: "SO", nameAr: "الصومال" },
  { code: "CHN", alpha2: "CN", nameAr: "الصين" },
  { code: "IRQ", alpha2: "IQ", nameAr: "العراق" },
  { code: "GAB", alpha2: "GA", nameAr: "الغابون" },
  { code: "VAT", alpha2: "VA", nameAr: "الفاتيكان" },
  { code: "PHL", alpha2: "PH", nameAr: "الفلبين" },
  { code: "CMR", alpha2: "CM", nameAr: "الكاميرون" },
  { code: "COG", alpha2: "CG", nameAr: "الكونغو - برازافيل" },
  { code: "COD", alpha2: "CD", nameAr: "الكونغو - كينشاسا" },
  { code: "KWT", alpha2: "KW", nameAr: "الكويت" },
  { code: "DEU", alpha2: "DE", nameAr: "ألمانيا" },
  { code: "MAR", alpha2: "MA", nameAr: "المغرب" },
  { code: "MEX", alpha2: "MX", nameAr: "المكسيك" },
  { code: "SAU", alpha2: "SA", nameAr: "المملكة العربية السعودية" },
  { code: "GBR", alpha2: "GB", nameAr: "المملكة المتحدة" },
  { code: "NOR", alpha2: "NO", nameAr: "النرويج" },
  { code: "AUT", alpha2: "AT", nameAr: "النمسا" },
  { code: "NER", alpha2: "NE", nameAr: "النيجر" },
  { code: "IND", alpha2: "IN", nameAr: "الهند" },
  { code: "USA", alpha2: "US", nameAr: "الولايات المتحدة" },
  { code: "JPN", alpha2: "JP", nameAr: "اليابان" },
  { code: "YEM", alpha2: "YE", nameAr: "اليمن" },
  { code: "GRC", alpha2: "GR", nameAr: "اليونان" },
  { code: "ATA", alpha2: "AQ", nameAr: "أنتاركتيكا" },
  { code: "ATG", alpha2: "AG", nameAr: "أنتيغوا وبربودا" },
  { code: "AND", alpha2: "AD", nameAr: "أندورا" },
  { code: "IDN", alpha2: "ID", nameAr: "إندونيسيا" },
  { code: "AGO", alpha2: "AO", nameAr: "أنغولا" },
  { code: "AIA", alpha2: "AI", nameAr: "أنغويلا" },
  { code: "URY", alpha2: "UY", nameAr: "أورغواي" },
  { code: "UZB", alpha2: "UZ", nameAr: "أوزبكستان" },
  { code: "UGA", alpha2: "UG", nameAr: "أوغندا" },
  { code: "UKR", alpha2: "UA", nameAr: "أوكرانيا" },
  { code: "IRN", alpha2: "IR", nameAr: "إيران" },
  { code: "IRL", alpha2: "IE", nameAr: "أيرلندا" },
  { code: "ITA", alpha2: "IT", nameAr: "إيطاليا" },
  { code: "PNG", alpha2: "PG", nameAr: "بابوا غينيا الجديدة" },
  { code: "PRY", alpha2: "PY", nameAr: "باراغواي" },
  { code: "PAK", alpha2: "PK", nameAr: "باكستان" },
  { code: "PLW", alpha2: "PW", nameAr: "بالاو" },
  { code: "BRB", alpha2: "BB", nameAr: "بربادوس" },
  { code: "BMU", alpha2: "BM", nameAr: "برمودا" },
  { code: "BRN", alpha2: "BN", nameAr: "بروناي" },
  { code: "BEL", alpha2: "BE", nameAr: "بلجيكا" },
  { code: "BGR", alpha2: "BG", nameAr: "بلغاريا" },
  { code: "BLZ", alpha2: "BZ", nameAr: "بليز" },
  { code: "BGD", alpha2: "BD", nameAr: "بنغلاديش" },
  { code: "PAN", alpha2: "PA", nameAr: "بنما" },
  { code: "BEN", alpha2: "BJ", nameAr: "بنين" },
  { code: "BTN", alpha2: "BT", nameAr: "بوتان" },
  { code: "BWA", alpha2: "BW", nameAr: "بوتسوانا" },
  { code: "PRI", alpha2: "PR", nameAr: "بورتوريكو" },
  { code: "BFA", alpha2: "BF", nameAr: "بوركينا فاسو" },
  { code: "BDI", alpha2: "BI", nameAr: "بوروندي" },
  { code: "POL", alpha2: "PL", nameAr: "بولندا" },
  { code: "BOL", alpha2: "BO", nameAr: "بوليفيا" },
  { code: "PYF", alpha2: "PF", nameAr: "بولينيزيا الفرنسية" },
  { code: "PER", alpha2: "PE", nameAr: "بيرو" },
  { code: "BLR", alpha2: "BY", nameAr: "بيلاروس" },
  { code: "THA", alpha2: "TH", nameAr: "تايلاند" },
  { code: "TWN", alpha2: "TW", nameAr: "تايوان" },
  { code: "TKM", alpha2: "TM", nameAr: "تركمانستان" },
  { code: "TUR", alpha2: "TR", nameAr: "تركيا" },
  { code: "TTO", alpha2: "TT", nameAr: "ترينيداد وتوباغو" },
  { code: "TCD", alpha2: "TD", nameAr: "تشاد" },
  { code: "CHL", alpha2: "CL", nameAr: "تشيلي" },
  { code: "TZA", alpha2: "TZ", nameAr: "تنزانيا" },
  { code: "TGO", alpha2: "TG", nameAr: "توغو" },
  { code: "TUV", alpha2: "TV", nameAr: "توفالو" },
  { code: "TKL", alpha2: "TK", nameAr: "توكيلاو" },
  { code: "TUN", alpha2: "TN", nameAr: "تونس" },
  { code: "TON", alpha2: "TO", nameAr: "تونغا" },
  { code: "TLS", alpha2: "TL", nameAr: "تيمور - ليشتي" },
  { code: "JAM", alpha2: "JM", nameAr: "جامايكا" },
  { code: "GIB", alpha2: "GI", nameAr: "جبل طارق" },
  { code: "ALA", alpha2: "AX", nameAr: "جزر آلاند" },
  { code: "BHS", alpha2: "BS", nameAr: "جزر البهاما" },
  { code: "COM", alpha2: "KM", nameAr: "جزر القمر" },
  { code: "MTQ", alpha2: "MQ", nameAr: "جزر المارتينيك" },
  { code: "MDV", alpha2: "MV", nameAr: "جزر المالديف" },
  { code: "UMI", alpha2: "UM", nameAr: "جزر الولايات المتحدة النائية" },
  { code: "PCN", alpha2: "PN", nameAr: "جزر بيتكيرن" },
  { code: "TCA", alpha2: "TC", nameAr: "جزر توركس وكايكوس" },
  { code: "SLB", alpha2: "SB", nameAr: "جزر سليمان" },
  { code: "FRO", alpha2: "FO", nameAr: "جزر فارو" },
  { code: "FLK", alpha2: "FK", nameAr: "جزر فوكلاند" },
  { code: "VIR", alpha2: "VI", nameAr: "جزر فيرجن الأمريكية" },
  { code: "VGB", alpha2: "VG", nameAr: "جزر فيرجن البريطانية" },
  { code: "CYM", alpha2: "KY", nameAr: "جزر كايمان" },
  { code: "COK", alpha2: "CK", nameAr: "جزر كوك" },
  { code: "CCK", alpha2: "CC", nameAr: "جزر كوكوس (كيلينغ)" },
  { code: "MHL", alpha2: "MH", nameAr: "جزر مارشال" },
  { code: "MNP", alpha2: "MP", nameAr: "جزر ماريانا الشمالية" },
  { code: "WLF", alpha2: "WF", nameAr: "جزر والس وفوتونا" },
  { code: "BVT", alpha2: "BV", nameAr: "جزيرة بوفيه" },
  { code: "CXR", alpha2: "CX", nameAr: "جزيرة كريسماس" },
  { code: "IMN", alpha2: "IM", nameAr: "جزيرة مان" },
  { code: "NFK", alpha2: "NF", nameAr: "جزيرة نورفولك" },
  { code: "HMD", alpha2: "HM", nameAr: "جزيرة هيرد وجزر ماكدونالد" },
  { code: "CAF", alpha2: "CF", nameAr: "جمهورية أفريقيا الوسطى" },
  { code: "DOM", alpha2: "DO", nameAr: "جمهورية الدومينيكان" },
  { code: "ZAF", alpha2: "ZA", nameAr: "جنوب أفريقيا" },
  { code: "SSD", alpha2: "SS", nameAr: "جنوب السودان" },
  { code: "GEO", alpha2: "GE", nameAr: "جورجيا" },
  { code: "SGS", alpha2: "GS", nameAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية" },
  { code: "DJI", alpha2: "DJ", nameAr: "جيبوتي" },
  { code: "JEY", alpha2: "JE", nameAr: "جيرسي" },
  { code: "DMA", alpha2: "DM", nameAr: "دومينيكا" },
  { code: "RWA", alpha2: "RW", nameAr: "رواندا" },
  { code: "RUS", alpha2: "RU", nameAr: "روسيا" },
  { code: "ROU", alpha2: "RO", nameAr: "رومانيا" },
  { code: "REU", alpha2: "RE", nameAr: "روينيون" },
  { code: "ZMB", alpha2: "ZM", nameAr: "زامبيا" },
  { code: "ZWE", alpha2: "ZW", nameAr: "زيمبابوي" },
  { code: "CIV", alpha2: "CI", nameAr: "ساحل العاج" },
  { code: "WSM", alpha2: "WS", nameAr: "ساموا" },
  { code: "ASM", alpha2: "AS", nameAr: "ساموا الأمريكية" },
  { code: "BLM", alpha2: "BL", nameAr: "سان بارتليمي" },
  { code: "SPM", alpha2: "PM", nameAr: "سان بيير ومكويلون" },
  { code: "MAF", alpha2: "MF", nameAr: "سان مارتن" },
  { code: "SMR", alpha2: "SM", nameAr: "سان مارينو" },
  { code: "VCT", alpha2: "VC", nameAr: "سانت فنسنت وجزر غرينادين" },
  { code: "KNA", alpha2: "KN", nameAr: "سانت كيتس ونيفيس" },
  { code: "LCA", alpha2: "LC", nameAr: "سانت لوسيا" },
  { code: "SXM", alpha2: "SX", nameAr: "سانت مارتن" },
  { code: "SHN", alpha2: "SH", nameAr: "سانت هيلينا" },
  { code: "STP", alpha2: "ST", nameAr: "ساو تومي وبرينسيبي" },
  { code: "LKA", alpha2: "LK", nameAr: "سريلانكا" },
  { code: "SJM", alpha2: "SJ", nameAr: "سفالبارد وجان ماين" },
  { code: "SVK", alpha2: "SK", nameAr: "سلوفاكيا" },
  { code: "SVN", alpha2: "SI", nameAr: "سلوفينيا" },
  { code: "SGP", alpha2: "SG", nameAr: "سنغافورة" },
  { code: "SYR", alpha2: "SY", nameAr: "سوريا" },
  { code: "SUR", alpha2: "SR", nameAr: "سورينام" },
  { code: "CHE", alpha2: "CH", nameAr: "سويسرا" },
  { code: "SLE", alpha2: "SL", nameAr: "سيراليون" },
  { code: "SYC", alpha2: "SC", nameAr: "سيشل" },
  { code: "SRB", alpha2: "RS", nameAr: "صربيا" },
  { code: "TJK", alpha2: "TJ", nameAr: "طاجيكستان" },
  { code: "OMN", alpha2: "OM", nameAr: "عُمان" },
  { code: "GMB", alpha2: "GM", nameAr: "غامبيا" },
  { code: "GHA", alpha2: "GH", nameAr: "غانا" },
  { code: "GRD", alpha2: "GD", nameAr: "غرينادا" },
  { code: "GRL", alpha2: "GL", nameAr: "غرينلاند" },
  { code: "GTM", alpha2: "GT", nameAr: "غواتيمالا" },
  { code: "GLP", alpha2: "GP", nameAr: "غوادلوب" },
  { code: "GUM", alpha2: "GU", nameAr: "غوام" },
  { code: "GUF", alpha2: "GF", nameAr: "غويانا الفرنسية" },
  { code: "GUY", alpha2: "GY", nameAr: "غيانا" },
  { code: "GGY", alpha2: "GG", nameAr: "غيرنزي" },
  { code: "GIN", alpha2: "GN", nameAr: "غينيا" },
  { code: "GNQ", alpha2: "GQ", nameAr: "غينيا الاستوائية" },
  { code: "GNB", alpha2: "GW", nameAr: "غينيا بيساو" },
  { code: "VUT", alpha2: "VU", nameAr: "فانواتو" },
  { code: "FRA", alpha2: "FR", nameAr: "فرنسا" },
  { code: "VEN", alpha2: "VE", nameAr: "فنزويلا" },
  { code: "FIN", alpha2: "FI", nameAr: "فنلندا" },
  { code: "VNM", alpha2: "VN", nameAr: "فيتنام" },
  { code: "FJI", alpha2: "FJ", nameAr: "فيجي" },
  { code: "CYP", alpha2: "CY", nameAr: "قبرص" },
  { code: "QAT", alpha2: "QA", nameAr: "قطر" },
  { code: "KGZ", alpha2: "KG", nameAr: "قيرغيزستان" },
  { code: "KAZ", alpha2: "KZ", nameAr: "كازاخستان" },
  { code: "NCL", alpha2: "NC", nameAr: "كاليدونيا الجديدة" },
  { code: "HRV", alpha2: "HR", nameAr: "كرواتيا" },
  { code: "KHM", alpha2: "KH", nameAr: "كمبوديا" },
  { code: "CAN", alpha2: "CA", nameAr: "كندا" },
  { code: "CUB", alpha2: "CU", nameAr: "كوبا" },
  { code: "CUW", alpha2: "CW", nameAr: "كوراساو" },
  { code: "KOR", alpha2: "KR", nameAr: "كوريا الجنوبية" },
  { code: "PRK", alpha2: "KP", nameAr: "كوريا الشمالية" },
  { code: "CRI", alpha2: "CR", nameAr: "كوستاريكا" },
  { code: "COL", alpha2: "CO", nameAr: "كولومبيا" },
  { code: "KIR", alpha2: "KI", nameAr: "كيريباتي" },
  { code: "KEN", alpha2: "KE", nameAr: "كينيا" },
  { code: "LVA", alpha2: "LV", nameAr: "لاتفيا" },
  { code: "LAO", alpha2: "LA", nameAr: "لاوس" },
  { code: "LBN", alpha2: "LB", nameAr: "لبنان" },
  { code: "LUX", alpha2: "LU", nameAr: "لوكسمبورغ" },
  { code: "LBY", alpha2: "LY", nameAr: "ليبيا" },
  { code: "LBR", alpha2: "LR", nameAr: "ليبيريا" },
  { code: "LTU", alpha2: "LT", nameAr: "ليتوانيا" },
  { code: "LIE", alpha2: "LI", nameAr: "ليختنشتاين" },
  { code: "LSO", alpha2: "LS", nameAr: "ليسوتو" },
  { code: "MLT", alpha2: "MT", nameAr: "مالطا" },
  { code: "MLI", alpha2: "ML", nameAr: "مالي" },
  { code: "MYS", alpha2: "MY", nameAr: "ماليزيا" },
  { code: "MYT", alpha2: "YT", nameAr: "مايوت" },
  { code: "MDG", alpha2: "MG", nameAr: "مدغشقر" },
  { code: "EGY", alpha2: "EG", nameAr: "مصر" },
  { code: "MKD", alpha2: "MK", nameAr: "مقدونيا الشمالية" },
  { code: "MWI", alpha2: "MW", nameAr: "ملاوي" },
  { code: "MAC", alpha2: "MO", nameAr: "منطقة ماكاو الإدارية الخاصة" },
  { code: "MNG", alpha2: "MN", nameAr: "منغوليا" },
  { code: "MRT", alpha2: "MR", nameAr: "موريتانيا" },
  { code: "MUS", alpha2: "MU", nameAr: "موريشيوس" },
  { code: "MOZ", alpha2: "MZ", nameAr: "موزمبيق" },
  { code: "MDA", alpha2: "MD", nameAr: "مولدوفا" },
  { code: "MCO", alpha2: "MC", nameAr: "موناكو" },
  { code: "MSR", alpha2: "MS", nameAr: "مونتسرات" },
  { code: "MMR", alpha2: "MM", nameAr: "ميانمار (بورما)" },
  { code: "FSM", alpha2: "FM", nameAr: "ميكرونيزيا" },
  { code: "NAM", alpha2: "NA", nameAr: "ناميبيا" },
  { code: "NRU", alpha2: "NR", nameAr: "ناورو" },
  { code: "NPL", alpha2: "NP", nameAr: "نيبال" },
  { code: "NGA", alpha2: "NG", nameAr: "نيجيريا" },
  { code: "NIC", alpha2: "NI", nameAr: "نيكاراغوا" },
  { code: "NZL", alpha2: "NZ", nameAr: "نيوزيلندا" },
  { code: "NIU", alpha2: "NU", nameAr: "نيوي" },
  { code: "HTI", alpha2: "HT", nameAr: "هايتي" },
  { code: "HND", alpha2: "HN", nameAr: "هندوراس" },
  { code: "HUN", alpha2: "HU", nameAr: "هنغاريا" },
  { code: "NLD", alpha2: "NL", nameAr: "هولندا" },
  { code: "BES", alpha2: "BQ", nameAr: "هولندا الكاريبية" },
  { code: "HKG", alpha2: "HK", nameAr: "هونغ كونغ الصينية (منطقة إدارية خاصة)" },
] as const;

const BY_CODE = new Map(NATIONALITIES.map((n) => [n.code, n]));

export const NATIONALITY_CODES = NATIONALITIES.map((n) => n.code) as [string, ...string[]];

export function isNationalityCode(value: string): boolean {
  return BY_CODE.has(value);
}

// Falls back to the raw stored value: a legacy row holding free text from
// before this module existed should still render as something, not blank.
export function nationalityLabel(code: string | null | undefined): string {
  if (!code) return "—";
  return BY_CODE.get(code)?.nameAr ?? code;
}
